name: ls on release

on:
  release:
    types: [published]

jobs:
  test:
    name: Try launching pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List files
        run: ls
